[package]
name = "valfisk"
version = "0.1.0"
edition = "2021"

license = "AGPL-3.0-only"
authors = ["Ryan Cao <hello@ryanccn.dev>"]


[dependencies]
anyhow = "1.0.75"
dotenvy = "0.15.7"
num = "0.4.1"
once_cell = "1.18.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "serenity-next", version = "0.5.5" }
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = [
  "rustls-tls",
  "json",
  "brotli",
] }
serde = { version = "1.0.189", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "fat"
codegen-units = 1
